In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/rainfaLLIndia.csv")
display(df)

                   subdivision  YEAR    JUN    JUL    AUG    SEP  JUN-SEP
0     ANDAMAN & NICOBAR ISLAND  1901  517.5  365.1  481.1  332.6   1696.3
1     ANDAMAN & NICOBAR ISLAND  1902  537.1  228.9  753.7  666.2   2185.9
2     ANDAMAN & NICOBAR ISLAND  1903  479.9  728.4  326.7  339.0   1874.0
3     ANDAMAN & NICOBAR ISLAND  1904  495.1  502.0  160.1  820.4   1977.6
4     ANDAMAN & NICOBAR ISLAND  1905  628.7  368.7  330.5  297.0   1624.9
...                        ...   ...    ...    ...    ...    ...      ...
4327                LAKSHDWEEP  2017  521.9  164.2  206.2  216.0   1108.3
4328                LAKSHDWEEP  2018  203.2  139.7  124.4   74.4    541.7
4329                LAKSHDWEEP  2019  242.5  489.4  338.4  156.7   1227.0
4330                LAKSHDWEEP  2020  265.4  476.2  269.6  334.3   1345.5
4331                LAKSHDWEEP  2021  160.0  156.5  319.5  154.9    790.9

[4332 rows x 7 columns]

In [ ]:
# sd0 = df.iloc[:19,:]  #tested whole prediction code by taking only 20 rows of andman&nicobar   ----working

all_subdivisons = df[df.duplicated(subset='subdivision', keep=False)]['subdivision'].unique()
# print(all_subdivisons)


all_subdivisons_list = []
for i in all_subdivisons:
  all_subdivisons_list.append(i)

# print(all_subdivisons_list)
# print(all_subdivisons_list[6])

for s in all_subdivisons_list :
 sd = df[df['subdivision']== s]
 # print(sd)

 df1 = sd.drop('subdivision', axis=1)
 # print(df1)

 x = df1.iloc[:,:1].values
 # print(x)

 y = df1.iloc[:,-1:].values
 # print(y)

 model = LinearRegression()
 model.fit(x,y)

 inYear = df['YEAR'].max()+1

#  subdivision = 'ANDAMAN & NICOBAR ISLAND'
 predicted_rainfall = model.predict([[inYear]])
 # print(f'Predicted Rainfall (Jun-Sep) for the year 2022: {predicted_rainfall[0]} mm')

 if predicted_rainfall>=12000.99:
   print(f'Highest Rainfall Predicted in {s} for the year {inYear} (June-Sept): upto approx. {predicted_rainfall[0]} mm')
 elif predicted_rainfall>=5000.99:
   print(f'Maximum Rainfall Predicted in {s} for the year {inYear} (June-Sept): upto approx. {predicted_rainfall[0]} mm')
 elif predicted_rainfall>=1000.99 or predicted_rainfall>=400.99:
   print(f' \033[1m Average \033[0m Rainfall Predicted in \033[1m{s}\033[0m for the year \033[1m{inYear}\033[0m (June-Sept): upto approx. {predicted_rainfall[0]} mm')
 elif predicted_rainfall>=250.99:
   print(f'Minimum Rainfall Predicted in {s} for the year {inYear} (June-Sept): upto approx. {predicted_rainfall[0]} mm')
 else :
   print(f'Drought Predicted in {s} for the year {inYear} (June-Sept): upto approx. {predicted_rainfall[0]} mm')

  Average  Rainfall Predicted in ANDAMAN & NICOBAR ISLAND for the year 2022 (June-Sept): upto approx. [1671.02602923] mm
  Average  Rainfall Predicted in ARUNACHAL PRADESH for the year 2022 (June-Sept): upto approx. [1320.69366146] mm
  Average  Rainfall Predicted in ASSAM & MEGHALAYA for the year 2022 (June-Sept): upto approx. [1654.64252066] mm
  Average  Rainfall Predicted in NAGALAND, MANIPUR, MIZORAM, TRIPURA for the year 2022 (June-Sept): upto approx. [1375.51710744] mm
  Average  Rainfall Predicted in SUB HIMALAYAN W.BENGAL & SIKKIM for the year 2022 (June-Sept): upto approx. [1965.03702479] mm
  Average  Rainfall Predicted in GANGETIC W.BENGAL for the year 2022 (June-Sept): upto approx. [1202.28380165] mm
  Average  Rainfall Predicted in ORISSA for the year 2022 (June-Sept): upto approx. [1131.24743802] mm
  Average  Rainfall Predicted in JHARKHAND for the year 2022 (June-Sept): upto approx. [991.47045455] mm
  Average  Rainfall Predicted in BIHAR for the year 2022 (June-Sept): upto approx. [946.89103306] mm
  Average  Rainfall Predicted in EAST UTTAR PRADESH for the year 2022 (June-Sept): upto approx. [782.19822314] mm
  Average  Rainfall Predicted in WEST UTTAR PRADESH for the year 2022 (June-Sept): upto approx. [667.20789256] mm
  Average  Rainfall Predicted in UTTARANCHAL for the year 2022 (June-Sept): upto approx. [1061.92628099] mm
  Average  Rainfall Predicted in HARYANA, DELHI & CHANDIGARH for the year 2022 (June-Sept): upto approx. [432.88475207] mm
  Average  Rainfall Predicted in PUNJAB for the year 2022 (June-Sept): upto approx. [466.57483471] mm
  Average  Rainfall Predicted in HIMACHAL PRADESH for the year 2022 (June-Sept): upto approx. [662.3361157] mm
  Average  Rainfall Predicted in JAMMU & KASHMIR for the year 2022 (June-Sept): upto approx. [539.73086777] mm
Minimum Rainfall Predicted in WEST RAJASTHAN for the year 2022 (June-Sept): upto approx. [285.22698347] mm
  Average  Rainfall Predicted in EAST RAJASTHAN for the year 2022 (June-Sept): upto approx. [626.38904959] mm
  Average  Rainfall Predicted in WEST MADHYA PRADESH for the year 2022 (June-Sept): upto approx. [911.99636364] mm
  Average  Rainfall Predicted in EAST MADHYA PRADESH for the year 2022 (June-Sept): upto approx. [997.76504132] mm
  Average  Rainfall Predicted in GUJARAT REGION for the year 2022 (June-Sept): upto approx. [919.79272727] mm
  Average  Rainfall Predicted in SAURASHTRA & KUTCH for the year 2022 (June-Sept): upto approx. [572.34433884] mm
  Average  Rainfall Predicted in KONKAN & GOA for the year 2022 (June-Sept): upto approx. [3096.15454545] mm
  Average  Rainfall Predicted in MADHYA MAHARASHTRA for the year 2022 (June-Sept): upto approx. [844.48619835] mm
  Average  Rainfall Predicted in MARATHWADA for the year 2022 (June-Sept): upto approx. [671.93438017] mm
  Average  Rainfall Predicted in VIDARBHA for the year 2022 (June-Sept): upto approx. [945.80669421] mm
  Average  Rainfall Predicted in CHATHISGARH for the year 2022 (June-Sept): upto approx. [1132.38363636] mm
  Average  Rainfall Predicted in COASTAL ANDHRA PRADESH & YANAM for the year 2022 (June-Sept): upto approx. [615.26338843] mm
  Average  Rainfall Predicted in TELANGANA for the year 2022 (June-Sept): upto approx. [748.48380165] mm
  Average  Rainfall Predicted in RAYALSEEMA for the year 2022 (June-Sept): upto approx. [409.71842975] mm
Minimum Rainfall Predicted in TAMIL NADU, PUDUCHERRY & KARAIKAL for the year 2022 (June-Sept): upto approx. [330.9127686] mm
  Average  Rainfall Predicted in COASTAL KARNATAKA for the year 2022 (June-Sept): upto approx. [3138.52958678] mm
  Average  Rainfall Predicted in NORTH INTERIOR KARNATAKA for the year 2022 (June-Sept): upto approx. [532.19103306] mm
  Average  Rainfall Predicted in SOUTH INTERIOR KARNATAKA for the year 2022 (June-Sept): upto approx. [756.72020661] mm
  Average  Rainfall Predicted in KERALA & MAHE for the year 2022 (June-Sept): upto approx. [1892.29855372] mm
  Average  Rainfall Predicted in LAKSHDWEEP for the year 2022 (June-Sept): upto approx. [1051.9443435] mm